### ISSUE TITLE
画像ありのプロフィール編集画面で、横向きにするとエラー

### ISSUE THREAD

**Issue by kazuki86** [kazuki86/SixCat#13]
横向きにすると落ちる。

**Comment by kazuki86** [comment]
エラーのスタックトレースを貼る。

01-22 19:44:24.559    9988-9988/jp.gr.java_conf.kazuki.sixcat E/dalvikvm-heap﹕ Out of memory on a 31390996-byte allocation.
01-22 19:44:24.569    9988-9988/jp.gr.java_conf.kazuki.sixcat E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: jp.gr.java_conf.kazuki.sixcat, PID: 9988
    java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
            at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:613)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:589)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:627)
            at jp.gr.java_conf.kazuki.sixcat.AbstractProfileEditFragment.getImageView(AbstractProfileEditFragment.java:323)
            at jp.gr.java_conf.kazuki.sixcat.AbstractProfileEditFragment.createRowView(AbstractProfileEditFragment.java:280)
            at jp.gr.java_conf.kazuki.sixcat.ProfileEditActivity$PlaceholderFragment.initializeView(ProfileEditActivity.java:277)
            at jp.gr.java_conf.kazuki.sixcat.AbstractProfileEditFragment.onCreateView(AbstractProfileEditFragment.java:76)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1917)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:544)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
            at android.app.Activity.performStart(Activity.java:5413)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2242)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2359)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3921)
            at android.app.ActivityThread.access$900(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5230)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
            at dalvik.system.NativeStart.main(Native Method)
