### ISSUE TITLE
画像があると保存時にエラー

### ISSUE THREAD

**Issue by kazuki86** [kazuki86/SixCat#14]
編集内容によらず、写真があるプロフィール編集画面で保存するとエラー発生。
一応保存自体はできてる

**Comment by kazuki86** [comment]
スタックトレースを貼る。＃１３と同じかな。

01-22 19:47:51.619  10506-10506/jp.gr.java_conf.kazuki.sixcat E/dalvikvm-heap﹕ Out of memory on a 31390996-byte allocation.
01-22 19:47:51.629  10506-10506/jp.gr.java_conf.kazuki.sixcat E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: jp.gr.java_conf.kazuki.sixcat, PID: 10506
    java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
            at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:613)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:589)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:627)
            at jp.gr.java_conf.kazuki.sixcat.ProfileDetailFragment.onCreateView(ProfileDetailFragment.java:132)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
            at android.app.Activity.performStart(Activity.java:5413)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2242)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2359)
            at android.app.ActivityThread.access$800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5230)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by kazuki86** [comment]
#12 , #13 と同じ問題。メモリリークを解消することで解決したのでClose
